version: '3.8'
services:
  mosquito:
    image: eclipse-mosquitto
    restart: unless-stopped
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

networks:
  proxy:
    external: true
